### ISSUE TITLE
Fails on relative paths

### ISSUE THREAD

**Issue by constgen** [xyyjk/babel-plugin-transform-jsx-url#2]
Relative paths are incorrectly resolved to the current file. Seems like they are not joined correctly but just concatenated as is with `root` (if defined in config). This JSX expression should work, but it doesn't

```jsx
<img src="./images/logo-jsx.svg" alt="" />
```

_Error_

```
Module not found: Error: Can't resolve 'C:\Users\const\Desktop\react\src./images/logo-jsx.svg' in 'C:\Users\const\Desktop\react\src'
```

**Comment by xyyjk** [comment]
Thanks for your feedback, this issue has been fixed
